rbac:
  # Role Hierarchy
  role_hierarchy:
    admin:
      - user
      - guest
    user:
      - guest
  
  # Permission Definitions
  permissions:
    admin:
      - read
      - write
      - delete
      - admin
      - audit
      - security
    user:
      - read
      - write
      - profile
    guest:
      - read
      - profile
  
  # Role Definitions
  roles:
    admin:
      description: Full system access
      permissions: [read, write, delete, admin, audit, security]
      risk_level: high
    user:
      description: Standard user access
      permissions: [read, write, profile]
      risk_level: medium
    guest:
      description: Limited access
      permissions: [read, profile]
      risk_level: low
  
  # Access Control Settings
  access_control:
    session_timeout: 3600
    max_sessions: 5
    rate_limit:
      requests_per_minute: 1000
      burst_limit: 500
    password_policy:
      min_length: 12
      require_special_chars: true
      require_numbers: true
      require_uppercase: true
      require_lowercase: true
  
  # Audit Settings
  audit:
    enabled: true
    log_level: INFO
    retention_days: 365
    risk_assessment:
      enabled: true
      threshold: medium
  
  # Compliance Settings
  compliance:
    gdpr_compliance: enabled
    data_retention: 90
    audit_trail: enabled
    access_logs: enabled
