groups:
- name: FinConnectAIAlerts
  rules:
  # High Error Rate Alert
  - alert: HighErrorRate
    expr: rate(customer_ai_prediction_errors_total[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High prediction error rate detected
      description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

  # High Latency Alert
  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(customer_ai_request_latency_seconds_bucket[5m])) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High request latency detected
      description: "95th percentile latency is {{ $value }}s for the last 5 minutes"

  # Low Model Accuracy Alert
  - alert: LowModelAccuracy
    expr: customer_ai_model_accuracy < 0.8
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: Low model accuracy detected
      description: "Model accuracy is {{ $value }} which is below threshold"

  # High Memory Usage Alert
  - alert: HighMemoryUsage
    expr: customer_ai_memory_usage_bytes > 1e9
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage detected
      description: "Memory usage is {{ $value | humanize }}B"

  # High CPU Usage Alert
  - alert: HighCPUUsage
    expr: customer_ai_cpu_usage_percent > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage detected
      description: "CPU usage is {{ $value }}%"

  # High Request Rate Alert
  - alert: HighRequestRate
    expr: rate(customer_ai_requests_total[5m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High request rate detected
      description: "Request rate is {{ $value }} requests per second"

  # Service Health Alert
  - alert: ServiceUnhealthy
    expr: up{job="customer-ai"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Service is down
      description: "Customer AI service is not responding"

  # Drift Detection Alert
  - alert: ModelDriftDetected
    expr: customer_ai_model_drift > 0.2
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: Model drift detected
      description: "Model drift score is {{ $value }}"

  # Data Quality Alert
  - alert: PoorDataQuality
    expr: customer_ai_data_quality_score < 0.9
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: Poor data quality detected
      description: "Data quality score is {{ $value }}"

  # Business Impact Alert
  - alert: LowBusinessValue
    expr: rate(customer_ai_business_value[1h]) < 100
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: Low business value generation
      description: "Business value generation rate is {{ $value }} per hour"
